# Generated by Django 4.2.11 on 2025-12-16 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_measure', models.CharField(default='50KG', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Grower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grower_no', models.CharField(max_length=20, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=50)),
                ('farm', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('hectares', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('field_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growers', to='growers.fieldofficer')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('delivery_note_no', models.CharField(blank=True, max_length=50)),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='growers.grower')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growers.inventoryitem')),
            ],
        ),
    ]
