# Generated by Django 4.2.11 on 2025-12-16 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='growers.inventoryitem'),
        ),
    ]
