# Generated by Django 4.2.11 on 2025-12-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growers', '0002_alter_allocation_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='grower',
            name='account_holder',
            field=models.CharField(blank=True, help_text='Full name as it appears on the bank statement', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grower',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='grower',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grower',
            name='branch_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='grower',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
